---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: awsdemo-hpa
  region: eu-west-1

managedNodeGroups:
  - name: default
    instanceType: t3.small
    desiredCapacity: 2

iam:
  withOIDC: true